In [ ]:
import xarray as xr
import intake,yaml,os
import intake_esm
import matplotlib
from matplotlib import pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
# pd.set_option('display.max_rows', None)
# directory = os.path.dirname(__file__)
directory = "./"

In [2]:
variables = [["slp","atmos_4xdaily"],
            ["precip","atmos_4xdaily_avg"],
            ["snow_tot","atmos_4xdaily_avg"],
            ["wind_ref","atmos_daily"],
            ["t_ref_max","atmos_daily"],
            ["t_ref_min","atmos_daily"],
            ["land_daily/snow","land_daily"],
            ["WVP","atmos"],
            ["ssh","ocean"],
            ["MLD_003","ocean"]]

In [24]:
var_df = pd.DataFrame(data=variables, columns=['variable_id','realm'])
var_df.to_csv("variables.csv", index=False)

In [33]:
len(var_df)

10

In [32]:
var_df['variable_id']

0                slp
1             precip
2           snow_tot
3           wind_ref
4          t_ref_max
5          t_ref_min
6    land_daily/snow
7                WVP
8                ssh
9            MLD_003
Name: variable_id, dtype: object

In [13]:
cat_url = "https://raw.githubusercontent.com/aradhakrishnanGFDL/sandbox/refs/heads/spear/cats/spear/mycatalog-spear.json"
cat = intake.open_esm_datastore(cat_url)

In [20]:
def search_to_subcat(output_name, catalog, list_of_variables):
    empty_cat = catalog.search()
    empty_cat.serialize(directory=directory, name=output_name, catalog_type="file")
    dfs = []
    for v in list_of_variables:
        dfs.append(catalog.search(realm=v[1], variable_id=v[0]).df)
    concat_df = pd.concat(dfs, ignore_index=True)
    concat_df.to_csv(directory+output_name+".csv", header=False, index=None, mode='a')
    return

In [21]:
search_to_subcat("test_empty", cat, variables)

Successfully wrote ESM catalog json file to: file:///home/aradick/Documents/scratch/SPEAR-test/test_empty.json

In [ ]:
def search_to_df(catalog, list_of_variables):
    dfs = []
    for v in list_of_variables:
        dfs.append(catalog.search(realm=v[1], variable_id=v[0]).df)
    concat_df = pd.concat(dfs, ignore_index=True)
    return concat_df

In [ ]:
df_filtered = search_to_df(cat, variables)
# df_filtered.to_csv("subcat_spear.csv", header=False, index=None, mode='a')

NameError: name 'cat' is not defined

In [61]:
cat.unique().variable_id

['alb_sfc',
 'evap',
 'hght',
 'high_cld_amt',
 'ice_mask',
 'prec_conv',
 'precip',
 'prec_ls',
 'rh_ref',
 'shflx',
 'slp_dyn',
 'slp',
 'snow_conv',
 'swdn_sfc_clr',
 'swdn_sfc',
 'swdn_toa_clr',
 'swdn_toa',
 'swup_sfc_clr',
 'swup_sfc',
 'swup_toa_clr',
 'swup_toa',
 'tot_cld_amt',
 't_ref_max',
 't_ref_min',
 't_ref',
 't_surf',
 'uq',
 'uq_vi',
 'u_ref',
 'ut',
 'ut_vi',
 'uu',
 'uu_vi',
 'uv',
 'uv_vi',
 'vcomp',
 'vort850',
 'vq',
 'vq_vi',
 'v_ref',
 'vt',
 'vt_vi',
 'vv',
 'vv_vi',
 'wind_ref',
 'WVP',
 'z200',
 'hfds',
 'IWP',
 'low_cld_amt',
 'lwdn_sfc_clr',
 'lwdn_sfc',
 'lwflx',
 'LWP',
 'lwup_sfc_clr',
 'lwup_sfc',
 'mid_cld_amt',
 'netrad_toa',
 'olr_clr',
 'olr',
 'omega',
 'rh',
 'sphum',
 'tau_x',
 'tau_y',
 'temp',
 'ucomp',
 'snow_ls',
 'ps',
 'qo3_col',
 'snow_tot',
 'cape',
 'cin',
 'pv350',
 'q_ref',
 'tm',
 'u200',
 'v300',
 'v850',
 'z300',
 'z500',
 'z850',
 'u850',
 'v200',
 'vort200',
 'q200',
 'q700',
 'q925',
 'q500',
 'q850',
 't200',
 't250',
 't500',
 't700',
 't925',
 'u500',
 'u50',
 'u250',
 'u925',
 'v250',
 'v500',
 'v925',
 'vort500',
 'z250',
 'z700',
 'z925',
 'q250',
 't850',
 'u700',
 'v700',
 'evs',
 'ficeberg',
 'fprec',
 'friver',
 'frunoff',
 'heat_content_cond',
 'heat_content_fprec',
 'heat_content_frunoff',
 'heat_content_lprec',
 'heat_content_lrunoff',
 'heat_content_massin',
 'heat_content_massout',
 'heat_content_surfwater',
 'Heat_PmE',
 'hfevapds',
 'hfibthermds',
 'hflso',
 'hfrainds',
 'hfrunoffds',
 'hfsifrazil',
 'hfsnthermds',
 'hfsso',
 'MLD_003_max',
 'MLD_003_min',
 'MLD_003',
 'net_heat_coupler',
 'net_heat_surface',
 'net_massin',
 'net_massout',
 'PRCmE',
 'prlq',
 'prsn',
 'p_surf',
 'rlntds',
 'rsntds',
 'S_adx_2d',
 'S_ady_2d',
 'salt_flux',
 'sensible',
 'sfdsi',
 'speed',
 'ssh',
 'sss',
 'sst_max',
 'sst_min',
 'SST',
 'SW',
 'T_adx_2d',
 'T_ady_2d',
 'tauuo',
 'latent',
 'lprec',
 'lrunoff',
 'LwLatSens',
 'LW',
 'ML_buoy_restrat',
 'tauvo',
 'taux',
 'tauy',
 'TKE_tidal',
 'ustar',
 'wfo',
 'uhml',
 'uh',
 'umo',
 'uo',
 'vhGM',
 'vhml',
 'vh',
 'vmo',
 'vo',
 'S_advection_xy',
 'Sh_tendency_vert_remap',
 'osaltpmdiff',
 'difvho',
 'frazil_heat_tendency',
 'opottempdiff',
 'opottemppmdiff',
 'opottemptend',
 'osaltdiff',
 'osalttend',
 'rhoinsitu',
 'rhopot0',
 'rhopot2',
 'rsdoabsorb',
 'so',
 'thetao',
 'uhGM',
 'T_advection_xy',
 'wmo',
 'wo',
 'boundary_forcing_heat_tendency',
 'boundary_forcing_salt_tendency',
 'Th_tendency_vert_remap']

In [ ]:
# subcat1 = cat.search(realm="land_daily")
subcat2 = cat.search(realm=["atmos_4xdaily", "atmos_daily"], variable_id="slp")

In [53]:
subcat1

In [ ]:
dfcat

,activity_id,institution_id,source_id,experiment_id,frequency,realm,table_id,member_id,grid_label,variable_id,time_range,chunk_freq,platform,dimensions,cell_methods,standard_name,path
0,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2031010100-2040123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
1,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2021010100-2030123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
2,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2071010100-2080123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
3,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2061010100-2070123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
4,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2081010100-2090123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
5,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2091010100-2100123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
6,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2011010100-2020123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
7,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2051010100-2060123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
8,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily_avg,NaN,NaN,NaN,precip,2041010100-2050123123,10yr,NaN,NaN,ts,Total_precipitation_rate,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
9,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2011010100-2020123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
10,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2051010100-2060123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
11,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2031010100-2040123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
12,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2041010100-2050123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
13,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2021010100-2030123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
14,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2061010100-2070123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
15,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2071010100-2080123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
16,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2091010100-2100123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...
17,dev,NaN,SPEAR,SPEAR_c192_o1_Scen_SSP585_IC2011_K50_ens_01_03,6hr,atmos_4xdaily,NaN,NaN,NaN,slp,2081010100-2090123123,10yr,NaN,NaN,ts,sea_level_pressure,/archive/a1r/SPEAR/SPEAR_c192_o1_Scen_SSP585_I...